### PR TITLE
Attempt to fix build problems on windows. (Discovered when trying to: luarocks install luafilesystem)

### PR DESCRIPTION
**Pull request by echiesse**
Problems whose fixes have been attempted:
- Compiler and linker options for MSVC must be passed with slashes instead of dashes.
- Libdir was wrong
- Was trying to link with a .dll instead of .lib.

The fixes here must be further worked out because they were made in place and are really BAD in the long term. But I don't know the project enough to fix in the proper locations.

They allowed me to successfully build luafilesystem but are really poor solutions

### CODE REVIEW

**Comment by Tieske** [comment]
@echiesse Have you tested your code on the supported toolchains? My guess is it fails on MinGW

**Comment by hishamhm** [comment]
> Compiler and linker options for MSVC must be passed with slashes instead of dashes.

It does? We have it running it MSVC with the Appveyor CI:

https://ci.appveyor.com/project/hishamhm/luarocks/build/3.0.0.552-test

> @echiesse Have you tested your code on the supported toolchains? My guess is it fails on MinGW

@Tieske It's failing on both MSVC and MinGW:

https://ci.appveyor.com/project/hishamhm/luarocks/build/2.2.1.553-test

@echiesse What version of MSVC did you test this on?

**Comment by echiesse** [comment]
@Tieske No, just MSVC. I didn't try MinGW.

@hishamhm Dashes are actually allowed. Just read it in the documentation (https://msdn.microsoft.com/en-us/library/610ecb4h.aspx). So it might be something else in my configuration that confused me about these options. 

I'm using Visual Studio 2015 and Windows10 Pro.

I'm getting the following error when trying a install from official LR:
`
c:\Eric\Programas\Lua\luarocks-2.4.2-win32\luarocks-2.4.2-win32>luarocks install luafilesystem
Installing https://luarocks.org/luafilesystem-1.6.3-2.src.rock
cl /nologo /MD /O2 -c -Fosrc/lfs.obj -IC:/PgmInst/Lua/5.1/include src/lfs.c
lfs.c
link -dll -def:lfs.def -out:lfs.dll C:/PgmInst/Lua/5.1/lua5.1.dll src/lfs.obj
Microsoft (R) Incremental Linker Version 14.00.23506.0
Copyright (C) Microsoft Corporation.  All rights reserved.

C:\PgmInst\Lua\5.1\lua5.1.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x2B8

Error: Build error: Failed compiling module lfs.dll
`
This has to do with the libpath and the file extension.

**Comment by Tieske** [comment]
@echiesse the LuaRocks installer spits out how it is configured, and iirc it uses `.lib` for msvc, and `.dll` for MinGW.

are you sure you installed it correctly? Can you retry and post the output?

**Comment by echiesse** [comment]
@Tieske Command line used to install:
`install /LUA C:\PgmInst\Lua\5.1 /P C:\PgmInst\Lua\LuaRocks /TREE C:\PgmInst\Lua\LuaRocks\tree`

**Comment by hishamhm** [comment]
@echiesse The new commit 3743dd7 is still breaking the build.

**Comment by Tieske** [comment]
@echiesse can you also post the output of the install command?

**Comment by Stanzilla** [comment]
@echiesse hey there, do you still want to do this?

**Comment by echiesse** [comment]
Sorry, I couldn't touch this code for some time. I'll be in a hurry for at
least the next 15 days. After that I'll be able to give attention to this
fix.

If for some reason it is causing any inconvenience, you may reject the pull
request and I resubmit appropriately when I have more time available.

Thank you for the reminder.

---
Eric Chiesse

**Comment by hishamhm** [comment]
@echiesse I'm closing this since the detection of compiler variables changed considerably in LuaRocks 3. Could you give LuaRocks 3 a try and let us know if it solves your issues?

You could try this all-in-one build: https://hisham.hm/win32/luarocks-dev-windows-32-8734df1.zip

**Comment by echiesse** [comment]
Thank you for the update.

I'll give it a try the next time I test my project luabibtex.

---
Eric

**Pull request closed without merging**
