### PR TITLE
fix: use realpath for find_program()

### PR DESCRIPTION
**Pull request by Freed-Wu**

### CODE REVIEW

**Comment by Tieske** [comment]
I'm not sure this is safe. Until recently macOS didn't have realpath, had to be installed separately.

**Comment by hishamhm** [comment]
hi @Freed-Wu, thanks for the PR! Can you give a bit more context on why you needed this?

Also, `realpath` is not very portable in non-Linux systems. We do have a `canonicalpath` function in the `configure` script that could be used in its stead.

**Comment by Freed-Wu** [comment]
In some case, we have a symlink to real lua to allow system exists many lua in different position.

**Comment by hishamhm** [comment]
@Freed-Wu could you please confirm that changing `realpath` to `canonicalpath` in that line would also work for your use-case? Thank you!

**Comment by Freed-Wu** [comment]
No, It will give me 'lua.h for Lua 5.1 not found'

**Comment by Freed-Wu** [comment]
Does macos have `readlink`?

`readlink -f` can get the path of symlink.

**Pull request closed without merging**
