### PR TITLE
add Windows testing

### PR DESCRIPTION
**Pull request by dundargoc**

### CODE REVIEW

**Comment by dundargoc** [comment]
Oh, luarocks tests Windows on appveyor for some reason. Closing then.

**Comment by Tieske** [comment]
maybe it is better to switch to GHA? the appveyor tests pre-date the Windows availability on Github

**Comment by dundargoc** [comment]
Alright, let's pivot the PR to move from appveyor to GHA then?

**Comment by hishamhm** [comment]
Is it faster, though? Looking at some job times for our Mac + Linux CI on Github:

https://github.com/luarocks/luarocks/actions/runs/3596546048

...versus job times for Windows testing on Appveyor:

https://ci.appveyor.com/project/hishamhm/luarocks/builds/46637899

...the tests are not exactly apples-to-apples, but at first glance it doesn't seem to be the case.

There's also the all-eggs-in-one-basket factor, too... (We've had to migrate CIs in the past, it's always annoying.)

**Comment by dundargoc** [comment]
> ...the tests are not exactly apples-to-apples, but at first glance it doesn't seem to be the case.

The appveyor run looks like it was cached, while the GHA wasn't?

> There's also the all-eggs-in-one-basket factor, too... (We've had to migrate CIs in the past, it's always annoying.)

Fair.

Anyway, I didn't mean to force a choice in CI provider, I just missed that Windows was being tested.

**Pull request closed without merging**
